import {
  Puzzle,
  MessageSquare,
  GitBranch,
  Settings,
  FileText,
  Search,
  Plus,
  Trash2,
  RefreshCw,
  Check,
  AlertCircle,
  Power,
  Database,
  Cloud,
  Cpu,
  Terminal,
  Layout,
  Columns,
  Rows,
  Maximize,
  Minimize,
  Eye,
  PenLine,
  Code,
  File,
  Folder,
  Image,
  Video,
  Music,
  User,
  Users,
  Bell,
  Calendar,
  Clock,
  ExternalLink,
  Link,
  Shield,
  Zap,
  type LucideProps,
} from "lucide-react";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  puzzle: Puzzle,
  "message-square": MessageSquare,
  "git-branch": GitBranch,
  settings: Settings,
  "file-text": FileText,
  search: Search,
  plus: Plus,
  trash: Trash2,
  "refresh-cw": RefreshCw,
  check: Check,
  "alert-circle": AlertCircle,
  power: Power,
  database: Database,
  cloud: Cloud,
  cpu: Cpu,
  terminal: Terminal,
  layout: Layout,
  columns: Columns,
  rows: Rows,
  maximize: Maximize,
  minimize: Minimize,
  eye: Eye,
  "pen-line": PenLine,
  code: Code,
  file: File,
  folder: Folder,
  image: Image,
  video: Video,
  music: Music,
  user: User,
  users: Users,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  "external-link": ExternalLink,
  link: Link,
  shield: Shield,
  zap: Zap,
};

interface PluginIconProps extends LucideProps {
  icon?: string;
  fallback?: React.ComponentType<LucideProps>;
}

export function PluginIcon({ icon, fallback: Fallback = Puzzle, ...props }: PluginIconProps) {
  const IconComponent = icon && ICON_MAP[icon] ? ICON_MAP[icon] : Fallback;
  return <IconComponent {...props} />;
}
