import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("lp", "routes/lp.tsx"),
  route("lp/ja", "routes/lp.tsx", { id: "lp-ja" }),
  route("terms", "routes/terms.tsx"),
  route("terms/ja", "routes/terms.tsx", { id: "terms-ja" }),
  route("policy", "routes/policy.tsx"),
  route("policy/ja", "routes/policy.tsx", { id: "policy-ja" }),
  route("manual/:chapter?", "routes/manual.tsx"),
  route("manual/ja/:chapter?", "routes/manual.tsx", { id: "manual-ja" }),
  route("auth/google", "routes/auth.google.tsx"),
  route("auth/google/callback", "routes/auth.google.callback.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("api/auth/unlock", "routes/api.auth.unlock.tsx"),
  route("settings", "routes/settings.tsx"),
  // API routes
  route("api/drive/files", "routes/api.drive.files.tsx"),
  route("api/drive/tree", "routes/api.drive.tree.tsx"),
  route("api/workflow/:id/execute", "routes/api.workflow.$id.execute.tsx"),
  route("api/workflow/ai-generate", "routes/api.workflow.ai-generate.tsx"),
  route("api/workflow/history", "routes/api.workflow.history.tsx"),
  route("api/workflow/request-history", "routes/api.workflow.request-history.tsx"),
  route("api/prompt-response", "routes/api.prompt-response.tsx"),
  route("api/chat", "routes/api.chat.tsx"),
  route("api/chat/history", "routes/api.chat.history.tsx"),
  route("api/settings/mcp-test", "routes/api.settings.mcp-test.tsx"),
  route("api/settings/mcp-oauth-token", "routes/api.settings.mcp-oauth-token.tsx"),
  route("auth/mcp-oauth-callback", "routes/auth.mcp-oauth-callback.tsx"),
  route("api/settings/rag-sync", "routes/api.settings.rag-sync.tsx"),
  route("api/settings/encryption", "routes/api.settings.encryption.tsx"),
  route("api/settings/edit-history", "routes/api.settings.edit-history.tsx"),
  route("api/settings/edit-history-stats", "routes/api.settings.edit-history-stats.tsx"),
  route("api/settings/edit-history-prune", "routes/api.settings.edit-history-prune.tsx"),
  route("api/mcp/tool-call", "routes/api.mcp.tool-call.tsx"),
  route("api/mcp/resource-read", "routes/api.mcp.resource-read.tsx"),
  route("api/search", "routes/api.search.tsx"),
  route("api/sync", "routes/api.sync.tsx"),
  route("api/drive/upload", "routes/api.drive.upload.tsx"),
  route("api/drive/temp", "routes/api.drive.temp.tsx"),
  // Public (no auth) — temp edit URLs for local editor integration
  route("api/temp-edit/:uuid/:fileName", "routes/api.temp-edit.$uuid.$fileName.tsx"),
  // Public (no auth) — serves published Drive files with correct Content-Type
  route("public/file/:fileId/:fileName", "routes/public.file.$fileId.$fileName.tsx"),
  route("api/plugins", "routes/api.plugins.tsx"),
  route("api/plugins/:id", "routes/api.plugins.$id.tsx"),
] satisfies RouteConfig;
